### ISSUE TITLE
Penser à une structure de spritesheet pour les textures

### ISSUE THREAD

**Issue by guillaumepn** [CatFishTeam/wooly-game#4]
Charger stone1, stone2, etc : pas terrible

Exemple: Avoir une spritesheet `stone.png` avec toutes les stones, puis dans le JSON de map, les charger dans ce style : 

```json
{
      "firstLayer": "grass",
      "secondLayer": {
        "texture" : "stone",
        "sprite" : 1, 
        "accessible": false,
        "deadly": false
      }
}
```

**Comment by Robilol** [comment]
Le zbeul vu qu'on a pas les même tailles d'image
